### ISSUE TITLE
Responsive 相关的东西在哪？

### ISSUE THREAD

**Issue by naiba** [gerry-momo/flutter_startup#1]
哈喽，你们怎么做自适应的？

**Comment by gerry-momo** [comment]
嗯 看你是希望什么样的自适应
这个项目你可以运行在手机和ipad上都看一下

**Comment by naiba** [comment]
基于中等手机屏幕下的设计图做出来在小屏幕上会溢出，你们没有遇到过问题吗
会用到如 flutter_screenutil 类的包做自适应
